// <auto-generated />
using System;
using SmartCoffeeMachine.Server.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoffeeMachineWebApi.Migrations
{
    [DbContext(typeof(CoffeeMachineDbContext))]
    partial class CoffeeMachineDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoffeeMachineWebApi.Models.CoffeeCup", b =>
                {
                    b.Property<int>("CoffeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoffeeId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CoffeeId");

                    b.ToTable("CoffeeCups");
                });

            modelBuilder.Entity("CoffeeMachineWebApi.Models.CoffeeMachine", b =>
                {
                    b.Property<long?>("CoffeeMachineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("CoffeeMachineID"));

                    b.Property<int>("BeanFeedState")
                        .HasColumnType("int");

                    b.Property<bool>("IsMakingCoffee")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOn")
                        .HasColumnType("bit");

                    b.Property<int>("WasteCoffeeState")
                        .HasColumnType("int");

                    b.Property<int>("WaterLevelState")
                        .HasColumnType("int");

                    b.Property<int>("WaterTrayState")
                        .HasColumnType("int");

                    b.HasKey("CoffeeMachineID");

                    b.ToTable("CoffeeMachineStatus");
                });
#pragma warning restore 612, 618
        }
    }
}
